question:
  types:
    single: "single"
    multiple: "multiple"
    text: "text"
  status:
    waiting: "waiting"
    accepted: "accepted"
  filter:
    all: "all"
admin:
  user:
    exam:
      all: "all"
exam:
  filter:
    all: "all"
pagination:
  questions_per_page: "5"
  subjects_per_page: "5"
  users_per_page: "5"
